complete 12
alexislam0207/news-server pull request #12
Opened 2023-11-22 10:23 UTC by alexislam0207

2023-11-22 11:01 UTC, johnhutcheon requested changes
Hey Alexis, nice work! Just see my comment and look to amend your test please 👍

2023-11-22 11:01 UTC, johnhutcheon commented on __tests__/app.test.js
> +describe("GET /api/articles/:article_id (now updated to include comment_count)", () => {
Rather than amending a previous test, could we have a new describe block for this task, with a new test showing that comment_count is there? This previous test should still pass if you remove line 96, as long as you have used a flexible matcher. 👍 If not, you may need to edit it slightly! 😄

2023-11-22 11:16 UTC, alexislam0207 commented on __tests__/app.test.js
> +describe("GET /api/articles/:article_id (now updated to include comment_count)", () => {
Thank you John, this is a new describe block for this task, the original test for "GET /api/articles/:article_id" is still there stating from line 48

2023-11-23 09:45 UTC, nickkagame approved these changes
All good!

2023-11-23 09:45 UTC, nickkagame commented on __tests__/app.test.js
> +describe("GET /api/articles/:article_id (now updated to include comment_count)", () => {
I think that the confusion was that you checked all of the properties when the other test was already doing this.  You just needed to test for comment count property really!  But no issue :)

2023-11-23 09:54 UTC, alexislam0207 commented on __tests__/app.test.js
> +describe("GET /api/articles/:article_id (now updated to include comment_count)", () => {
Yes, that makes sense. I'll change it to just check the comment count for this test. Thank you for the suggestion.

2023-11-23 09:54 UTC, merged